### ISSUE TITLE
Some files are not minified.

### ISSUE THREAD

**Issue by ikedat16** [matsuyoido/gradle-frontend-plugin#11]
指定ディレクトリ配下のjs,cssファイルの内、一部のファイルが圧縮されない。
ファイル名末尾（拡張子除く）の最後の1文字が以下のいずれかの場合に対象外になっているように見える。
- '.'
- 'm'
- 'i'
- 'n'

※恐らく`*.min.js`等を対象外にしようとしていると思いますが、glob文が誤っているようです
https://github.com/matsuyoido/gradle-frontend-plugin/blob/f170670f5ac894050555244ff471b09e1515b5fd/plugin/src/main/java/com/matsuyoido/plugin/frontend/task/Minifier.java#L11

**Comment by matsuyoido** [comment]
@ikedat16 

バグのご報告、ありがとうございました。

対応が遅くなりましたが、こちらのバグに対応しております。

2.0.2 のバージョンをご利用いただければ解消されているかと思いますが、ご確認いただき問題ないようでしたらClose していただければと思います。

引き続き、何かありましたら Issues を作成していただければと思います。

**Comment by ikedat16** [comment]
2.0.2を適用し、minify対象外になっていたファイルが対象になることを確認しました。  
お忙しい中ご対応ありがとうございます。  
closeします。
